name: CI/CD

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    frontend-build:
        name: Frontend Build
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: frontend
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3
            - name: Use Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18
                  cache: "yarn"
                  cache-dependency-path: frontend/yarn.lock
            - name: Install Dependencies
              run: yarn install --frozen-lockfile
            - name: Build Astro
              run: yarn build
    cdk-build:
        name: CDK Build
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: cdk
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3
            - name: Use Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18
                  cache: "yarn"
                  cache-dependency-path: cdk/yarn.lock
            - name: Install Dependencies
              run: yarn install --frozen-lockfile
            - name: Check The Code Style
              run: yarn format:check
            - name: Lint The Codebase
              run: yarn lint
